version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=mba
      - MYSQL_ROOT_PASSWORD=mba
      - MYSQL_USER=mba
      - MYSQL_PASSWORD=mba

  spring-boot:
    restart: always
    image: spring-boot
    # command: "java -jar ./build/libs/mba-0.0.1-SNAPSHOT.jar"
    build:
      context: ./server
    ports:
      - 8080:8080
    volumes:
      - springdata:/usr/src:rw
      - ./server/:/server/
    depends_on:
      - mysql
      - kafka

  react:
    build:
      context: ./client
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./client/:/client
      - ./client/node_modules/:/client/node_modules
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true
    tty: true
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mba-chat:1:1"   # Topic명:Partition개수:Replica개수
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  dbdata:
  springdata: